[tool.poetry]
name = "haccytrees"
version = "0.1.0"
description = ""
authors = ["Michael Buehlmann <buehlmann.michi@gmail.com>"]

[tool.poetry.scripts]
haccytrees-convert = "haccytrees.scripts.treenodes2forest:cli"

[tool.poetry.dependencies]
python = ">=3.8.0,<3.11"
numpy = "^1.20.0"
matplotlib = "^3.5.0"
numba = "^0.55.1"
click = "^8.0.4"
toml = "^0.10.2"
pygio = { git = "https://git.cels.anl.gov/hacc/genericio.git"}
colossus = "^1.2.19"
scipy = "^1.8.0"
Jinja2 = "^3.1.2"
sphinx-click = "^4.2.0"
mpi4py = "^3.1.3"
h5py = "^3.7.0"
drawSvg = "^1.9.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipykernel = "^6.10.0"
flake8 = "^4.0.1"
doc8 = "^0.10.1"
rstcheck = "^3.3.1"
black = "^22.3.0"
Sphinx = "^5.0.1"
sphinx-rtd-theme = "^1.0.0"
sphinxcontrib-napoleon = "^0.7"
numpydoc = "^1.4.0"
notebook = "^6.5.2"
matplotlib = "^3.6.2"

[tool.black]
line-length = 88
target-version = ["py38"]
include = '\.pyi?$'
exclude = '\.git|\.venv|build|_build|dist'

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
